// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdgarRepo.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20241205231842_NetIncomeLosses")]
    partial class NetIncomeLosses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Company", b =>
                {
                    b.Property<int>("Cik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cik");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("YearlyNetIncomeLoss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyCik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCik");

                    b.ToTable("YearNetIncomeLoss");
                });

            modelBuilder.Entity("YearlyNetIncomeLoss", b =>
                {
                    b.HasOne("Company", null)
                        .WithMany("YearlyNetIncomeLosses")
                        .HasForeignKey("CompanyCik");
                });

            modelBuilder.Entity("Company", b =>
                {
                    b.Navigation("YearlyNetIncomeLosses");
                });
#pragma warning restore 612, 618
        }
    }
}
