@EdgarFundingCalculator_HostAddress = http://localhost:5164

GET {{EdgarFundingCalculator_HostAddress}}/companies/
Accept: application/json
###

GET {{EdgarFundingCalculator_HostAddress}}/companies?firstLetter=a
Accept: application/json
###
